version: "3.8"
services:

  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: interview
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pass123
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase
    volumes:
      - ./liquibase/changelogs:/liquibase/changelogs
#      - ./liquibase/migrations:/liquibase/migrations
    command: #["--changeLogFile=/liquibase/changelog.xml", "--defaultsFile=/liquibase/liquibase.properties", "update"]
      - "--url=jdbc:postgresql://pgdb:5432/interview"
      - "--changeLogFile=/changelogs/changelog.xml"
      - "--defaultsFile=/liquibase.properties"
      - "--username=pguser"
      - "--password=pass123"
      - "update"
    depends_on:
      pgdb:
        condition: service_started

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: pguser@bhart.com
      PGADMIN_DEFAULT_PASSWORD: pass123
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_SETUP_EMAIL: pguser@bhart.com
      PGADMIN_SETUP_PASSWORD: pass123
      PGADMIN_SERVER_MODE: 'True'
      PGADMIN_SERVER_NAME: 'interview'
      PGADMIN_SERVER_HOST: 'pgdb'
      PGADMIN_SERVER_PORT: '5432'
      PGADMIN_SERVER_MAINTENANCE_DB: 'postgres'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      pgdb:
        condition: service_started
      liquibase:
        condition: service_completed_successfully

volumes:
  local_pgdata:
  pgadmin-data: